server:
    port: 8088
spring:
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        url: jdbc:postgresql://postgresqldb:5432/postgres
        username: isa_user
        password: isa_password
    liquibase:
        change-log: db/changelog/db.changelog-master.xml
    freemarker:
        expose-request-attributes: true
        suffix: .ftl

jwt:
    expiration-time: 300000000